export const Prenda = [{
    id: 1,
    name: 'Campera nike rompeviento',
    paragraph:'calidad premium',
    thumbnail:'../../assets/Images/Campera-nike.jpeg',
    price: '27.800',
},
{
    id: 2,
    name: 'Remera adidas negra',
    paragraph: 'calidad premium',
    thumbnail:'../../assets/Images/Remera-adidas.jpg',
    price: 16.799,
},
{
    id: 3,
    name: 'Zapatillas air force 1 nike',
    paragraph: 'calidad premium',
    thumbnail:'../../assets/Images/nike-air-force.jpg',
    price: 54.900,
},
{
    id: 4,
    name: 'Zapatillas adidas superstar blanca',
    paragraph: 'calidad premium',
    thumbnail:'../../assets/Images/adidas-superstar-blanca.jpg',
    price: 24.999,
},
{
    id: 5,
    name: 'Campera de abrigo adidas mujer',
    paragraph: 'calidad premium',
    thumbnail:'../../assets/Images/campera-adidas-mujer-rosa-1.jpg',
    price: 24.500,
},
{
    id: 6,
    name: 'Botines nike mercurial',
    paragraph: 'calidad premium',
    thumbnail:'../../assets/Images/botines-mercurial.jpg',
    price: 37.599,
},];